use healthcaredb;

-- query 1 Total revenue generated by each doctor

SELECT 
    d.name AS doctor_name,
    d.specialization,
    SUM(b.total_fee) AS total_revenue
FROM 
    Doctor d
JOIN 
    Appointments a ON d.doctor_id = a.doctor_id
JOIN 
    Billing b ON a.appointments_id = b.appointments_id
WHERE 
    b.payment_status = 'Paid'
GROUP BY 
    d.name, d.specialization
ORDER BY 
    total_revenue DESC;